export const CARS_LOADED = "CARS_LOADED";
export const COLORS_LOADED = "COLORS_LOADED";
export const MANUFACTURER_LOADED = "MANUFACTURER_LOADED";
export const FILTER_CARS = "FILTER_CARS";
export const SORT_CARS = "SORT_CARS";
export const FILTERS_SELECTED = "FILTERS_SELECTED";
export const PAGE_SELECTED = "PAGE_SELECTED";
export const SORT_SELECTED = "SORT_SELECTED";
export const CAR_BY_STOCK_NUMBER_LOADED = "CAR_BY_STOCK_NUMBER_LOADED";
export const CAR_BY_STOCK_NUMBER_ISFAVORITE = "CAR_BY_STOCK_NUMBER_ISFAVORITE";

export const GET_COLORS = "GET_COLORS";
export const GET_MANUFACTURERS = "GET_MANUFACTURERS";
export const GET_SORT_LIST = "GET_SORT_LIST";

export const SWITCH_LOAGINDG = "SWITCH_LOAGINDG";
